version: "3"

services:
  docsify:
    build: .
    volumes:
      - ./public:/home/docsify/public:ro
    ports:
      - 3000:3000
      - 35729:35729
    environment:
      CHOKIDAR_USEPOLLING: 1
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80
    links:
      - docsify
