# Project Information
site_name: docs.mochizuki.moe
site_url: https://docs.mochizuki.moe/
site_author: Natsuneko

# Preview Controls
use_directory_urls: true

# Git Repository
repo_url: https://github.com/mika-f/docs.mochizuki.moe
repo_name: mika-f/docs.mochizuki.moe
edit_uri: edit/master/docs

# Copyright
copyright: Copyright &copy 2020-2021 Natsuneko (Natsuneko Laboratory)

# Extra Resources
extra_css:
  - assets/css/colors.css
  - assets/css/extras.css
  - assets/css/figure.css
  - assets/css/highlight.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/medium-zoom@1.0.6/dist/medium-zoom.min.js
  - assets/js/medium-zoom.js

# Header Navigation
nav:
  - Home: index.md
  - Unity:
      Home: unity/index.md
      Atlasization:
        ホーム: unity/atlasization/index.md
        ガイド:
          インストール: unity/atlasization/guides/getting-started.md
          使い方: unity/atlasization/guides/how-to-use.md
        その他:
          既存の不具合: unity/atlasization/known-bugs.md
          利用規約: unity/atlasization/terms.md
          更新履歴: unity/atlasization/changelog.md
      Constraint By Humanoid:
        ホーム: unity/constraint-by-humanoid/index.md
        ガイド:
          インストール: unity/constraint-by-humanoid/guides/getting-started.md
          使い方: unity/constraint-by-humanoid/guides/how-to-use.md
        その他:
          利用規約: unity/constraint-by-humanoid/terms.md
          更新履歴: unity/constraint-by-humanoid/changelog.md
      Particle Effects:
        Home: unity/particle-system/index.md
        General:
          Getting Started: unity/particle-system/guides/getting-started.md
        Packages:
          "#001": unity/particle-system/packages/001.md
          "#002": unity/particle-system/packages/002.md
          "#003": unity/particle-system/packages/003.md
        Others:
          Terms: unity/particle-system/terms.md
          Changelog: unity/particle-system/changelog.md
      Sakura Shader:
        Home: unity/sakura-shader/index.md
        Guides:
          Installation: unity/sakura-shader/guides/getting-started.md
          How to use: unity/sakura-shader/guides/how-to-use.md
          Choose the Shader: unity/sakura-shader/guides/choose-the-shader.md
          Variants:
            Lyrics: unity/sakura-shader/guides/variants/lyrics.md
            Particles: unity/sakura-shader/guides/variants/particles.md
            ScreenFX: unity/sakura-shader/guides/variants/screen-fx.md
            Skybox: unity/sakura-shader/guides/variants/skybox.md
            Unlit: unity/sakura-shader/guides/variants/unlit.md
        Others:
          Terms: unity/sakura-shader/terms.md
          Changelog: unity/sakura-shader/changelog.md
      uProjection:
        ホーム: unity/u-projection/index.md
        ガイド:
          インストール: unity/u-projection/guides/getting-started.md
          使い方: unity/u-projection/guides/how-to-use.md
          変数一覧: unity/u-projection/guides/variables.md
        その他:
          利用規約: unity/u-projection/terms.md
          更新履歴: unity/u-projection/changelog.md
      Wireframe Shader:
        ホーム: unity/wireframe-shader/index.md
        ガイド:
          インストール: unity/wireframe-shader/guides/getting-started.md
          バリアント:
            シェーダーの選び方: unity/wireframe-shader/guides/variants/index.md
            Opaque: unity/wireframe-shader/guides/variants/opaque.md
            Transparent: unity/wireframe-shader/guides/variants/transparent.md
            Particle Transparent: unity/wireframe-shader/guides/variants/particle-transparent.md
        その他:
          利用規約: unity/wireframe-shader/terms.md
          更新履歴: unity/wireframe-shader/changelog.md
  - VRChat:
      Home: vrchat/index.md
      Asset Merger:
        ホーム: vrchat/asset-merger/index.md
        ガイド:
          インストール: vrchat/asset-merger/guides/getting-started.md
          使い方:
            前準備: vrchat/asset-merger/guides/how-to-use.md
            Animator Controller: vrchat/asset-merger/guides/how-to-use/animator-controller.md
            Expression Parameters: vrchat/asset-merger/guides/how-to-use/expression-parameters.md
            Expressions Menu: vrchat/asset-merger/guides/how-to-use/expressions-menu.md
          テスト済みツール: vrchat/asset-merger/guides/tested-tools.md
        その他:
          利用規約: vrchat/asset-merger/terms.md
          更新履歴: vrchat/asset-merger/changelog.md
      Fukidashi System:
        ホーム: vrchat/fukidashi-system/index.md
        ガイド:
          インストール: vrchat/fukidashi-system/guides/getting-started.md
          使い方: vrchat/fukidashi-system/guides/how-to-use.md
          カスタマイズ: vrchat/fukidashi-system/guides/customize.md
        その他:
          利用規約: vrchat/fukidashi-system/terms.md
          更新履歴: vrchat/fukidashi-system/changelog.md
      SDK2 Compatible Viewer:
        ホーム: vrchat/sdk2-compat-view/index.md
        ガイド:
          インストール: vrchat/sdk2-compat-view/guides/getting-started.md
          使い方: vrchat/sdk2-compat-view/guides/how-to-use.md
        その他:
          利用規約: vrchat/sdk2-compat-view/terms.md
          更新履歴: vrchat/sdk2-compat-view/changelog.md
  - Udon Rabbit:
      Home: udon-rabbit/index.md
      共通:
        インストール: udon-rabbit/guides/getting-started.md
      Packages:
        Analyzer:
          ホーム: udon-rabbit/packages/analyzer/index.md
          ガイド:
            導入方法: udon-rabbit/packages/analyzer/guides/getting-started.md
          アナライザー:
            各項目について: udon-rabbit/packages/analyzer/analyzers/index.md
            URA0001: udon-rabbit/packages/analyzer/analyzers/URA0001.md
            URA0002: udon-rabbit/packages/analyzer/analyzers/URA0002.md
            URA0003: udon-rabbit/packages/analyzer/analyzers/URA0003.md
            URA0004: udon-rabbit/packages/analyzer/analyzers/URA0004.md
            URA0005: udon-rabbit/packages/analyzer/analyzers/URA0005.md
            URA0006: udon-rabbit/packages/analyzer/analyzers/URA0006.md
            URA0007: udon-rabbit/packages/analyzer/analyzers/URA0007.md
            URA0008: udon-rabbit/packages/analyzer/analyzers/URA0008.md
            URA0009: udon-rabbit/packages/analyzer/analyzers/URA0009.md
            URA0010: udon-rabbit/packages/analyzer/analyzers/URA0010.md
            URA0011: udon-rabbit/packages/analyzer/analyzers/URA0011.md
            URA0012: udon-rabbit/packages/analyzer/analyzers/URA0012.md
            URA0013: udon-rabbit/packages/analyzer/analyzers/URA0012.md
            URA0014: udon-rabbit/packages/analyzer/analyzers/URA0012.md
            URA0015: udon-rabbit/packages/analyzer/analyzers/URA0012.md
            URA0016: udon-rabbit/packages/analyzer/analyzers/URA0012.md
            URA0017: udon-rabbit/packages/analyzer/analyzers/URA0012.md
            URA0018: udon-rabbit/packages/analyzer/analyzers/URA0012.md
            URA0019: udon-rabbit/packages/analyzer/analyzers/URA0012.md
            URA0020: udon-rabbit/packages/analyzer/analyzers/URA0012.md
        Interop:
          ホーム: udon-rabbit/packages/interop/index.md
          ライセンスについて: udon-rabbit/packages/interop/license.md
          ユーザー向け:
            設定方法: udon-rabbit/packages/interop/users/how-to-use.md
            対応パッケージ: udon-rabbit/packages/interop/users/packages.md
          開発者向け:
            開発の準備: udon-rabbit/packages/interop/developers/getting-started.md
            プロトコルについて: udon-rabbit/packages/interop/developers/protocol.md
            Event Listener Class: udon-rabbit/packages/interop/developers/event-listener.md
        Object Fitter:
          ホーム: udon-rabbit/packages/object-fitter/index.md
          ライセンスについて: udon-rabbit/packages/object-fitter/license.md
          設定方法: udon-rabbit/packages/object-fitter/how-to-use.md
          カスタマイズ: udon-rabbit/packages/object-fitter/customize.md
          ヒント: udon-rabbit/packages/object-fitter/hint.md
        Synchronized Animator:
          ホーム: udon-rabbit/packages/synchronized-animator/index.md
          設定方法: udon-rabbit/packages/synchronized-animator/how-to-use.md
          動作の仕組みについて: udon-rabbit/packages/synchronized-animator/how-it-works.md
      その他:
        利用規約: udon-rabbit/terms.md
        更新履歴: udon-rabbit/changelog.md
  - Archives: downloads/index.md
  - Announcements:
      2021/04/22: announcement/20210422-stop-distribution-of-all-products-in-natsuneko-laboratory.md
  - Contact: contact.md

# Theme Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    scheme: slate
    primary: light blue

# MkDocs & Theme Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - fontawesome_markdown
  - footnotes
  - meta
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
      toc_depth: 3

# MkDocs Plugins
plugins:
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Tokyo
      locale: en
      fallback_to_build_date: true
  - redirects:
      redirect_maps:
        AssetMerger/index.md: vrchat/asset-merger/index.md
        AssetMerger/Guide/Installation.md: vrchat/asset-merger/guides/getting-started.md
        AssetMerger/Guide/HowToUse.md: vrchat/asset-merger/guides/how-to-use.md
        AssetMerger/Guide/TestedTools.md: vrchat/asset-merger/guides/tested-tools.md
        AssetMerger/Advanced/AnimatorController.md: vrchat/asset-merger/index.md # TODO: Provide Advanced Pages
        AssetMerger/Contact.md: vrchat/asset-merger/terms.md
        AssetMerger/Changelog.md: vrchat/asset-merger/changelog.md
        Atlasization/index.md: unity/atlasization/index.md
        Atlasization/Guide/Installation.md: unity/atlasization/guides/getting-started.md
        Atlasization/Guide/HowToUse.md: unity/atlasization/guides/how-to-use.md
        Atlasization/Bugs.md: unity/atlasization/known-bugs.md
        Atlasization/Contact.md: unity/atlasization/terms.md
        Atlasization/Changelog.md: unity/atlasization/changelog.md
        ConstraintByHumanoid/index.md: unity/constraint-by-humanoid/index.md
        ConstraintByHumanoid/Installation.md: unity/constraint-by-humanoid/guides/getting-started.md
        ConstraintByHumanoid/HowToUse.md: unity/constraint-by-humanoid/guides/how-to-use.md
        ConstraintByHumanoid/Contact.md: unity/constraint-by-humanoid/terms.md
        ConstraintByHumanoid/Changelog.md: unity/constraint-by-humanoid/changelog.md
        FukidashiSystem/Guide/Installation.md: vrchat/fukidashi-system/guides/getting-started.md
        FukidashiSystem/Guide/HowToUse.md: vrchat/fukidashi-system/guides/how-to-use.md
        FukidashiSystem/Guide/Modification.md: vrchat/fukidashi-system/guides/customize.md
        FukidashiSystem/Contact.md: vrchat/fukidashi-system/terms.md
        FukidashiSystem/Changelog.md: vrchat/fukidashi-system/changelog.md
        SDK2CompatView/index.md: vrchat/sdk2-compat-view/index.md
        SDK2CompatView/Guide/Installation.md: vrchat/sdk2-compat-view/guides/getting-started.md
        SDK2CompatView/Guide/HowToUse.md: vrchat/sdk2-compat-view/guides/how-to-use.md
        UdonRabbit/index.md: udon-rabbit/index.md
        UdonRabbit/Guide/Installation.md: udon-rabbit/guides/getting-started.md
        UdonRabbit/Guide/FeatureRequest.md: udon-rabbit/terms.md
        UdonRabbit/Packages/Kitsune.md: udon-rabbit/index.md
        UdonRabbit/Packages/ObjectFitter.md: udon-rabbit/packages/object-fitter/how-to-use.md
        UdonRabbit/Packages/SynchronizedAnimator.md: udon-rabbit/packages/synchronized-animator/how-to-use.md
        UdonRabbit/Terms.md: udon-rabbit/terms.md
        WireframeShader/index.md: unity/wireframe-shader/index.md
        WireframeShader/Guide/Installation.md: unity/wireframe-shader/guides/getting-started.md
        WireframeShader/Guide/HowToUse.md: unity/wireframe-shader/guides/variants/index.md
        WireframeShader/Terms.md: unity/wireframe-shader/terms.md
        WireframeShader/Contact.md: unity/wireframe-shader/terms.md
        WireframeShader/Changelog.md: unity/wireframe-shader/changelog.md
